//go:build !ignore_autogenerated

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *PrivateDNSRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PrivateDNSRecord) DeepCopy() *PrivateDNSRecord {
	if in == nil {
		return nil
	}
	out := new(PrivateDNSRecord)
	*out = *in
	out.ObjectMeta = *in.ObjectMeta.DeepCopy()
	out.Spec.Values = append([]string(nil), in.Spec.Values...)
	out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	return out
}

func (in *PrivateDNSRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PrivateDNSRecordList) DeepCopy() *PrivateDNSRecordList {
	if in == nil {
		return nil
	}
	out := new(PrivateDNSRecordList)
	*out = *in
	out.ListMeta = in.ListMeta
	out.Items = make([]PrivateDNSRecord, len(in.Items))
	for i := range in.Items {
		out.Items[i] = *in.Items[i].DeepCopy()
	}
	return out
}

func (in *PrivateDNSZone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PrivateDNSZone) DeepCopy() *PrivateDNSZone {
	if in == nil {
		return nil
	}
	out := new(PrivateDNSZone)
	*out = *in
	out.ObjectMeta = *in.ObjectMeta.DeepCopy()
	out.Spec.AllowedNamespaces.MatchNames = append([]string(nil), in.Spec.AllowedNamespaces.MatchNames...)
	out.Spec.Records = make([]PrivateDNSRecordSpecInline, len(in.Spec.Records))
	copy(out.Spec.Records, in.Spec.Records)
	for i := range out.Spec.Records {
		out.Spec.Records[i].Values = append([]string(nil), in.Spec.Records[i].Values...)
	}
	out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
	return out
}

func (in *PrivateDNSZoneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *PrivateDNSZoneList) DeepCopy() *PrivateDNSZoneList {
	if in == nil {
		return nil
	}
	out := new(PrivateDNSZoneList)
	*out = *in
	out.ListMeta = in.ListMeta
	out.Items = make([]PrivateDNSZone, len(in.Items))
	for i := range in.Items {
		out.Items[i] = *in.Items[i].DeepCopy()
	}
	return out
}
